# Generated by Django 3.1.2 on 2020-11-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_summary',
            field=models.TextField(default='this is a summary'),
        ),
    ]
