# Generated by Django 3.1.2 on 2020-11-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_book_book_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=200)),
                ('employee_address', models.CharField(max_length=200)),
                ('employee_phone', models.CharField(max_length=200)),
            ],
        ),
    ]
