# Generated by Django 3.1.2 on 2020-11-03 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelstry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('student_address', models.CharField(max_length=200)),
                ('student_department', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
